defaults:
  delete_older_than_days: 30
  mode: dry-run # All operations default to dry-run for safety
  log_level: INFO
  log_file: dirclean.log
  clean_broken_symlinks: false # Default to false for safety

rules:
  - paths:
      - ~/Downloads
      - ~/Documents/temp
    delete_older_than_days: 7
    min_file_size: 1MB
    mode: dry-run
    clean_broken_symlinks: true # Enable for specific directories

  - paths:
      - /tmp/*
      - /var/tmp/*
    delete_older_than_days: 1
    max_file_size: 100MB
    mode: dry-run
    clean_broken_symlinks: false
