name: Build Go Program

on:
  release:
    types:
      - published  # Trigger when a new release is published
      - edited     # Trigger when an existing release is edited

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    strategy:
      matrix:
        platform:
          - os: darwin
            arch: arm64
            binary_name: dirclean-darwin-arm64
          - os: linux
            arch: amd64
            binary_name: dirclean-linux-amd64

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Specify the Go version you want to use

      # Build the Go program for the target platform
      - name: Build
        run: |
          GOOS=${{ matrix.platform.os }} GOARCH=${{ matrix.platform.arch }} go build -o ${{ matrix.platform.binary_name }} ./dirclean.go

      # Upload the compiled binary to the release
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}  # The upload URL for the release
          asset_path: ${{ matrix.platform.binary_name }}      # Path to the binary
          asset_name: ${{ matrix.platform.binary_name }}      # Name of the asset
          asset_content_type: application/octet-stream       # Content type for binary files