name: Build Go Program

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    strategy:
      matrix:
        platform:
          - os: darwin
            arch: arm64
            binary_name: dirclean-darwin-arm64
          - os: linux
            arch: amd64
            binary_name: dirclean-linux-amd64

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Specify the Go version you want to use

      # Build the Go program for the target platform
      - name: Build
        run: |
          GOOS=${{ matrix.platform.os }} GOARCH=${{ matrix.platform.arch }} go build -o ${{ matrix.platform.binary_name }} ./dirclean.go

      # Upload the compiled binary as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.binary_name }}
          path: ${{ matrix.platform.binary_name }}